# Initial state.
px: 0
py: 0
pz: 0
# Below initialization with roll and pitch.
# Hamilton quaternion taken *verbatim* from a ROS bag file.
# yaw set to zero 45 dense best. This initialization together with NO minus sign
# at the velocity from radar gives best result.
#qw: 0.9999992
#qx: -0.0012992
#qy: 0.0000025
#qz: 0
# Below init quaternion for `radar_bag_1_square_45_dense_slow.bag`.
#qw: 0.001961
#qx: 0.042885
#qy: 0.001298
#qz: 0.999077
# Below init quaternion for `awr_1.bag`.
#qw: -0.999701
#qx: 0.001199
#qy: 0.016235
#qz: -0.018250
# Below init quaternion for `awr_4.bag`.
#qw: -0.999787
#qx: 0.003297
#qy: 0.013711
#qz: -0.015087
# Below init quaternion for `awr_5.bag` - does not converge.
#qw: 0.999407
#qx: -0.001548
#qy: -0.014289
#qz: 0.031287
# Below init quaternion for `awr_8.bag`.
#qw: -0.700457
#qx: -0.012840
#qy: 0.009032
#qz: -0.713522
# Below init quaternion for `awr_10.bag`.
#qw: -0.999865
#qx: 0.000998
#qy: 0.015314
#qz: 0.005860
# Below init quaternion for `awr_3.bag`.
#qw: -0.999648
#qx: -0.001628
#qy: 0.017251
#qz: -0.020073
# Below init quaternion for `awr_9.bag`.
#qw: 0.999471
#qx: -0.001514
#qy: -0.015584
#qz: 0.028497
# Below init quaternion for `awr_10.bag`.
#qw: -0.999865
#qx: 0.000998
#qy: 0.015314
#qz: 0.005860
# Below init quaternion for `awr_6.bag`.
#qw: 0.999824
#qx: -0.000124
#qy: -0.015638
#qz: -0.010378
# Below init quaternion for `awr_7.bag`.
qw: 0.999863
qx: -0.001926
qy: -0.014326
qz: -0.008075

# Below init quaternion for flights from 04/12/2022.
#qw: 1
#qx: 0
#qy: 0
#qz: 0

# Below initialization with pitch only (iros).
# Quaternion used for IROS.
#qw: 0.9990668
#qx: 0
#qy: -0.0431925
#qz: 0
vx: 0
vy: 0
vz: 0
b_wx: 0
b_wy: 0
b_wz: 0
b_ax: 0
b_ay: 0
b_az: 0
# Parameters.
noise_acc: 0.0083
noise_accbias: 0.00083
noise_gyr: 0.0013
noise_gyrbias: 0.00013
noise_qwv: 0.0
noise_qri: 0.0
noise_pri: 0.0
# Distance to feature.
# Best - 0.2
# 0.04
noise_meas1: 0.04
# IMU.
noise_meas2: 0.01
# Velocity.
# Best - 0.037
noise_meas3: 0.035
# Persistent feature noise. 0.4
noise_meas4: 0.04

# Below calibration for `awr_1 - 10` bags from 22.08.22.
q_riw: 0.9170601
q_rix: 0
q_riy: 0.3987491
q_riz: 0
p_rix: 0.075
p_riy: -0.01
p_riz: -0.04

# Below calibration for flights from 04/12/2022.
#q_riw: -0.8733046
#q_rix: 0
#q_riy: -0.4871745
#q_riz: 0
#p_rix: 0.065
#p_riy: -0.005
#p_riz: -0.01

# Parameters not directly used in the implementation - only
# kept to reuse elements from ssf.
noise_qwv: 0.0
noise_aux: 0.0
noise_scale: 0.0
# Noise parameters for persistent features. 0.1
noise_pf_x: 0.1
noise_pf_y: 0.1
noise_pf_z: 0.1
